import React from "react";
import Popover from "material-ui/Popover/Popover";
import { Modal, Button } from "react-materialize";

export default class Article4 extends React.Component {
  render() {
    return (
      <section
        className="article4 row"
        style={{
          background:
            "url(./public/content/images/articles/article4-background.svg) no-repeat",
          backgroundSize: "cover"
        }}
      >
        <div className="article4-text-content row col s5">
          <h1 className="article4-header col s12">Reveal</h1>
          <h2 className="article4-sub-header col s12">New songs</h2>
          <p>
            Eco is a global currency not controlled by any single individual,
            organization, or nation. Our mission is to distribute the majority
            of the economic value generated by the Eco platform to our community
            to create a more equitable distribution of resources.
          </p>
          <a>Read this link</a>
          <img
            className="slider-button"
            src={"./public/content/images/articles/article4-button.svg"}
            alt="Kiwi standing on oval"
          />
        </div>
        <div
          className="article4-slider"
          style={{
            backgroundImage:
              "url(./public/content/images/main/hash-background.svg)",
            display:"flex",
            justifyContent: "center",
            alignItem: "center"

          }}
        >
          <img
            className=""
            style={{ width: "500px" }}
            src={"./public/content/images/articles/article4-icon.svg"}
            alt="Kiwi standing on oval"
          />
        </div>
        <div className="dot-left" id="21" />
        <div className="dot-right" id="22" />
        <div
          className="bottom-info col s12"
          style={{
            backgroundImage:
              "url(./public/content/images/main/hash-background.svg)"
          }}
        >
          <div className="bottom-info-content" />
        </div>
      </section>
    );
  }
}
